sciurus17_examples/scripts/waist_joint_trajectory_example.py

腰ヨー軸のサンプルについて次の点を修正しました。
- 関数＆変数名が不適切だったので修正
- 指定した角度へ指定した時間で遷移できるように機能を追加
- コメントを追加

#22 modify waist trajectory example

---

sciurus17_control/README.md

Add controller readme

---

sciurus17_examples/scripts/pick_and_place_left_arm_demo.py
sciurus17_examples/scripts/pick_and_place_right_arm_demo.py
sciurus17_examples/scripts/pick_and_place_two_arm_demo.py

delete wait for rviz

---

sciurus17_description/urdf/sciurus17_with_vehicle.urdf
sciurus17_gazebo/launch/sciurus17_with_vehicle.launch
sciurus17_gazebo/worlds/vehicle.world
sciurus17_moveit_config/launch/planning_context_with_vehicle.launch
sciurus17_moveit_config/launch/sciurus17_planning_with_vehicle.launch

add some file for vehicle to use gazebo

add some file for vehicle

---

sciurus17_bringup/launch/sciurus17_bringup_with_vehicle.launch

add sciurus17 bringup file for vehicle

add bringup launch

---

sciurus17_control/package.xml

gripper_action_controllerを実行時依存関係に追加しました。

Add depend

---

sciurus17_examples/package.xml
sciurus17_examples/scripts/chest_camera_tracking.py
sciurus17_examples/scripts/depth_camera_example.py
sciurus17_examples/scripts/depth_camera_tracking.py
sciurus17_examples/scripts/head_camera_tracking.py

デプスカメラを使用したサンプルです。
ボールトラッキングのコードをもとに、画像処理のコードを変更しています。

Add depth camera sample #34

---

sciurus17_vision/launch/realsense.launch

#44 を解決するために、`rs_rgbd.launch`から`rs_camera.launch`を使用するように書き換えました。
今までと同じコードで動くように`/camera/depth/color/points`を`/camera/depth_registered/points`にremapしています。
確認おねがいします。

Change rs_rgbd.launch to rs_camera.launch

---

sciurus17_examples/scripts/chest_camera_tracking.py
sciurus17_examples/scripts/head_camera_tracking.py

#56 に対応しました。
カメラサンプル実行中、shutdownと同時に首（腰）を初期値位置に戻します。
初期位置に戻るときは、ゆっくり動作します。

Return to initial position on shutdown_hook. 

---

sciurus17_description/urdf/sciurus17_head.xacro

Fix head_camera_joint of URDF

---

sciurus17_control/include/sciurus17_control/joint_control.h

Fix #78 for VC++

---

.travis.yml

Travis CIで、KineticとMelodicの両方の環境でテスト（ビルド）できるようにしました。

udpate .travis.yml for ROS Kinetic & Melodic

---

README.ja.md
README.md
sciurus17_examples/README.ja.md
sciurus17_examples/README.md

日本語のドキュメントを英訳するプルリクエストです。
できるだけ、[CRANE-X7](https://github.com/rt-net/crane_x7_ros/pull/105)と同じ文章になるように翻訳してます。
添削お願いします。
変更リスト

Translate README.md

---

sciurus17_bringup/launch/sciurus17_bringup.launch

Fix sciurus17_bringup.launch

---

sciurus17_moveit_config/.setup_assistant

MoveIt Setup Assistantでsciurus17のモデルをロードできるように修正しました。

fix .setup_assistant file to load sciurus17 model

---

sciurus17_examples/src/object_detection.cpp

腰を回したときに点群座標が現実とずれる問題があったので修正しました。
- lookupTransfromの実行をmain関数からコールバック関数に移動しました

move lookupTransfrom execution into callback to update tf every loop

---

README.en.md
README.md
sciurus17_control/README.md
sciurus17_examples/README.en.md
sciurus17_examples/README.md

#100 の対応です。画像の参照元をrt-net.github.io/images に変更します。

Port images from the images branch to rt-net.github.io/images

---

sciurus17_control/config/sciurus17_control1.yaml
sciurus17_control/config/sciurus17_fake_control1.yaml
sciurus17_control/launch/sciurus17_fake_control.launch
sciurus17_description/urdf/sciurus17.urdf.xacro
sciurus17_description/urdf/sciurus17_gazebo.xacro
sciurus17_examples/README.md
sciurus17_gazebo/launch/sciurus17_with_table.launch
sciurus17_gazebo/worlds/table.world

右腕を電流制御モードに切り替えてSciurus17を動かすサンプルを追加します。
本PRではサンプルプログラム（スクリプト）は追加されません。
別PRで電流制御で手首、グリッパーを動かすサンプルプログラムを実装する予定です。
本PRでは下記の変更を実施します。
- 引数で`hardware_interface`を切り替えられるようにxacroファイルを変更
- Gazeboで右腕を電流制御に切り替えられるように`launch`ファイルを編集
- 電流制御ros_controller用のPIDゲインをyamlファイルに追加
- READMEに説明を追記
- Gazeboの画面を明るくするため、worldファイルを編集
#80 が関連Issueです。本PRでクローズすべきかは相談が必要です。
ROS Melodicにて実機とGazeboで動作確認しました。

Add a current control example

---

sciurus17_control/CMakeLists.txt
sciurus17_examples/CMakeLists.txt
sciurus17_gazebo/CMakeLists.txt
sciurus17_tools/CMakeLists.txt

#110 の対応です。
`catkin_make install`コマンドでインストールされないファイルがあったので、修正しました。
#110 
`catkin_make instal`lコマンドを実行し、ファイルがインストールされたことを確認しました。
`install/setup.zsh`を読み込み、gazeboの`box_stacking_example`サンプルが実行されることを確認しました。
```sh
$ cd ~/catkin_ws
$ catkin_make install
$ ls install/share/sciurus17_control 
cmake  config  launch  package.xml
$ ls install/lib/sciurus17_control  
preset_reconfigure.py  sciurus17_control
$ ls install/share/sciurus17_examples 
cmake  launch  package.xml
$ ls install/lib/sciurus17_examples 
box_stacking_example.py    hand_position_publisher_example.py  pick_and_place_right_arm_demo.py
chest_camera_tracking.py   head_camera_tracking.py             pick_and_place_two_arm_demo.py
control_effort_wrist.py    neck_joint_trajectory_example.py    preset_pid_gain_example.py …
```

Fix CMakeLists.txt for catkin_make install.

---

.ci.rosinstall
.github/workflows/industrial_ci.yml
README.en.md
README.md
sciurus17_description/urdf/sciurus17_gazebo.xacro
sciurus17_examples/src/object_detection.cpp
sciurus17_gazebo/package.xml

これまで、realsense_rosとroboticsgroup_gazebo_mimic_joint_pluginパッケージはソースビルドしていました。
これをバイナリインストール（aptによるインストール）に変更します。
変更点：
- industrial_ci.yml、.ci.rosinstall
- CIからrealesnse_rosとroboticsgroup_gazebo_mimic_joint_pluginのソースビルド箇所が取り除かれます
- README.en.md、README.md 
- インストール方法を更新します
- sciurus17_gazebo.xacro
- プラグインを`libroboticsgroup_upatras_gazebo_mimic_joint_plugin.so`に変更します
- `libroboticsgroup_gazebo_mimic_joint_plugin.so`は非推奨です
- object_detection.cpp ( 箱積み上げサンプルで使用しているソースファイル)
- PointCloudトピックのframe_idが`camera_depth_optical_frame`から`camera_color_optical_frame`に変更されました
- 参考PR：https://github.com/IntelRealSense/realsense-ros/pull/1819
- frame_idの変更に影響されないように、ソースコードを修正します
- sciurus17_gazebo/package.xml
- roboticsgroup_upatras_gazebo_mimic_joint_pluginの依存関係を追加します
#113 をクローズできます …

realsense_rosとroboticsgroup_gazebo_mimic_joint_pluginをバイナリインストールに変更

---

sciurus17_examples/README.en.md
sciurus17_examples/README.md

箱積みサンプルの動画URLを変更します。
サムネイルをクリックし、動画サイトに移動することを確認しています。

箱積みサンプル動画のURLを変更

---

sciurus17_moveit_config/config/sciurus17.srdf

goup_stateに登録されている姿勢をbringup時の姿勢と同じものに設定しました。
このPRによりサンプル実行前の姿勢とサンプル実行後の姿勢が統一されます。
しません
下記コマンドでSciurus17を起動し、RVizからgroup_stateを確認しました。
```
roslaunch sciurus17_bringup sciurus17_bringup.launch
```

goup_stateの姿勢変更

---

sciurus17/package.xml
sciurus17_bringup/package.xml
sciurus17_control/package.xml
sciurus17_description/package.xml
sciurus17_examples/package.xml
sciurus17_gazebo/package.xml
sciurus17_moveit_config/package.xml
sciurus17_msgs/package.xml
sciurus17_tools/package.xml
sciurus17_vision/package.xml

現時点での最新コミットをバージョン1.0.0としてリリースするため、package.xmlのversionタグを更新します。
いいえ
package.xmlの更新のためテスト未実施です。

package.xmlのversionタグを1.0.0に更新

---

sciurus17_gazebo/gui/gui.config

Gazebo GUIのカメラ画角はデフォルトが90°で歪みが大きく見づらいため、50°に変更しました。
変更前
変更後
しません。
シミュレータを起動しカメラの画角が狭くなっていることを確認しました。
```
ros2 launch sciurus17_gazebo sciurus17_with_table.launch.py
```
ないです

Gazebo GUIのカメラ画角を50°に変更

---

sciurus17/package.xml
sciurus17_control/package.xml
sciurus17_examples/package.xml
sciurus17_gazebo/package.xml
sciurus17_moveit_config/package.xml
sciurus17_tools/package.xml

バージョンタグを2.0.0から3.0.0に変更しています。
しません。
ドキュメントのみの更新です。
ありません

Prepare for release 3.0.0

---

sciurus17_examples/README.md
sciurus17_gazebo/CMakeLists.txt
sciurus17_gazebo/config/bridge.yaml
sciurus17_gazebo/launch/sciurus17_with_table.launch.py
sciurus17_moveit_config/config/moveit.rviz

- https://github.com/rt-net/sciurus17_description/pull/13 で追加されるGazebo上のカメラのtopicをbridgeする設定を追加しました
- 上記PRをpullしてから動作確認お願いします
しません。
下記コマンドを実行し、画像のように頭部点群、胸部カメラ映像がRVizで見えることを確認しました。
```
ros2 launch sciurus17_gazebo sciurus17_with_table.launch.py
```
下記コマンドを実行し、点群、映像が配信されなくなることを確認しました。
```
ros2 launch sciurus17_gazebo sciurus17_with_table.launch.py use_chest_camera:=false use_head_camera:=false
```

Gazebo上のカメラのbridge設定を追加
